pool:
 vmImage: 'ubuntu-latest' 
variables:
- group: Talend Configuration
- name: project_name
  value: 'AZUREPIPELINE'
- name: job_name
  value: 'joindatadb'
- name: job_version
  value: '0.1'   
steps:
  - task: DownloadSecureFile@1
    name: settings_xml
    inputs:
      secureFile: settings.xml

  - task: DownloadSecureFile@1
    name: license
    inputs:
      secureFile: license

  - task: DownloadSecureFile@1
    name: pom_xml
    inputs:
      secureFile: sample_pom.xml

  - task: DownloadSecureFile@1
    name: cibuilder
    inputs:
      secureFile: Talend-CI-Builder-Maven-Plugin-20211109_1610-V8.0.1builder-maven-plugin-8.0.1.zip
- task: ExtractFiles@1

     - task: Maven@3
    displayName: 'Maven Install builder plugin'
    inputs:
      mavenPomFile: '$(pom_xml.secureFilePath)'
      goals: 'install:install-file' 
      options: '--batch-mode --settings $(settings_xml.secureFilePath) '
      mavenOptions: |
        -Dfile=./builder/Talend-CI-Builder-Maven-Plugin-20211109_1610-V8.0.1 8.0.1/builder-maven-plugin-8.0.1.jar
        -DpomFile=./builder/Talend-CI-Builder-Maven-Plugin-20211109_1610-V8.0.18.0.1/builder-maven-plugin-8.0.1.pom
  
# mavenPomFile: '$(Build.Repository.LocalPath)/$(project_name)/poms/pom.xml'
# mavenPomFile: '$(pom_xml.secureFilePath)'
- task: Maven@3
    displayName: 'Maven Install P2 and generate Poms'
    inputs:
      mavenPomFile: '$(pom_xml.secureFilePath)'
      goals: 'org.talend.ci:builder-maven-plugin:8.0.1:generateAllPoms' 
      options: '--batch-mode --settings $(settings_xml.secureFilePath) $(talend_ci_config)'
      publishJUnitResults: false
	  - task: CmdLine@2
    displayName: 'List the modules / available jobs to be built'
    inputs:
      script: |
        pwd
        cat $(project_name)/poms/pom.xml | sed '/<modules>/,/<\/modules>/!d' 
		- task: Maven@3
    displayName: 'Maven Build & Publish Talend jobs'	
    inputs:
        mavenPomFile: '$(project_name)/poms/pom.xml'
        goals: 'deploy' 
#compile / deploy
        options: '--batch-mode --settings $(settings_xml.secureFilePath) -pl $(jobs_to_build) -am -fae $(talend_ci_config)'  


